#!/usr/bin/env python3
"""
Generate YARA rules from the Giskard-AI/prompt-injections dataset.

Usage:
    python nackensec/scripts/generate_giskard_rules.py /tmp/giskard-pi

Output:
    nackensec/rules/community/giskard_injections.yara
"""

from __future__ import annotations

import csv
import hashlib
import sys
import textwrap
from pathlib import Path


OUTPUT_PATH = Path(__file__).parent.parent / "rules" / "community" / "giskard_injections.yara"

# Max strings per rule to avoid compiler limits
MAX_STRINGS_PER_RULE = 200

# Minimum payload length (very short strings cause too many false positives)
MIN_LENGTH = 15

# Maximum payload length for a YARA string literal
MAX_LENGTH = 120


def sanitize_yara_string(payload: str) -> str | None:
    """
    Convert a payload string to a safe YARA literal.
    Returns None if the payload should be skipped.
    """
    s = payload.strip().strip('"\'')

    # Skip very short or very long payloads
    if len(s) < MIN_LENGTH or len(s) > MAX_LENGTH:
        return None

    # Skip payloads with binary/non-printable characters
    if any(ord(c) > 126 for c in s):
        return None

    # Escape backslashes and double-quotes for YARA
    s = s.replace("\\", "\\\\").replace('"', '\\"')

    return s


def payload_var_name(index: int, payload: str) -> str:
    h = hashlib.sha256(payload.encode()).hexdigest()[:6]
    return f"$g{index:04d}_{h}"


def find_csv_files(dataset_dir: Path) -> list[Path]:
    return sorted(dataset_dir.rglob("*.csv"))


def extract_payloads(csv_files: list[Path]) -> list[str]:
    payloads: list[str] = []
    seen: set[str] = set()

    text_columns = {"text", "prompt", "injection", "payload", "content", "input"}

    for csv_path in csv_files:
        try:
            with open(csv_path, encoding="utf-8", errors="replace") as f:
                reader = csv.DictReader(f)
                if reader.fieldnames is None:
                    continue

                # Find which column has the payload text
                col = None
                for fn in reader.fieldnames:
                    if fn.lower() in text_columns:
                        col = fn
                        break
                if col is None and reader.fieldnames:
                    col = reader.fieldnames[0]  # Fall back to first column

                for row in reader:
                    raw = row.get(col or "", "").strip()
                    if raw and raw not in seen:
                        seen.add(raw)
                        payloads.append(raw)
        except Exception as e:
            print(f"Warning: could not parse {csv_path}: {e}", file=sys.stderr)

    return payloads


def generate_yara(payloads: list[str]) -> str:
    """Generate YARA rule content from a list of payload strings."""
    valid: list[tuple[str, str]] = []  # (var_name, sanitized_payload)

    for i, payload in enumerate(payloads):
        sanitized = sanitize_yara_string(payload)
        if sanitized is None:
            continue
        var_name = payload_var_name(len(valid), payload)
        valid.append((var_name, sanitized))

    if not valid:
        return ""

    # Split into chunks of MAX_STRINGS_PER_RULE
    chunks = [valid[i: i + MAX_STRINGS_PER_RULE] for i in range(0, len(valid), MAX_STRINGS_PER_RULE)]

    rules: list[str] = []
    for chunk_idx, chunk in enumerate(chunks):
        strings_block = "\n".join(
            f'        {name} = "{payload}" nocase'
            for name, payload in chunk
        )
        rule_name = f"giskard_prompt_injection_{chunk_idx:02d}"
        rule = textwrap.dedent(f"""\
            rule {rule_name} {{
                meta:
                    author = "NäckenSec (generated from Giskard-AI/prompt-injections)"
                    description = "Prompt injection payloads from Giskard dataset (chunk {chunk_idx})"
                    source = "https://github.com/Giskard-AI/prompt-injections"
                    license = "Apache-2.0"
                    generated = "true"

                strings:
            {strings_block}

                condition:
                    any of them
            }}
        """)
        rules.append(rule)

    header = textwrap.dedent(f"""\
        //////////////////////////////////////////////////////////
        // Giskard Prompt Injection YARA Rules
        // Auto-generated by nackensec/scripts/generate_giskard_rules.py
        // Source: https://github.com/Giskard-AI/prompt-injections
        // License: Apache-2.0
        // Total payloads: {len(valid)}
        // Rules: {len(chunks)}
        //
        // DO NOT EDIT — regenerate with:
        //   python nackensec/scripts/generate_giskard_rules.py /path/to/giskard-pi
        //////////////////////////////////////////////////////////

    """)

    return header + "\n\n".join(rules) + "\n"


def main() -> None:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <path-to-giskard-dataset>", file=sys.stderr)
        sys.exit(1)

    dataset_dir = Path(sys.argv[1])
    if not dataset_dir.is_dir():
        print(f"Error: {dataset_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    csv_files = find_csv_files(dataset_dir)
    if not csv_files:
        print(f"Error: no CSV files found in {dataset_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(csv_files)} CSV file(s)", file=sys.stderr)
    payloads = extract_payloads(csv_files)
    print(f"Extracted {len(payloads)} unique payloads", file=sys.stderr)

    yara_content = generate_yara(payloads)
    if not yara_content:
        print("Warning: no valid YARA strings generated", file=sys.stderr)
        sys.exit(1)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(yara_content, encoding="utf-8")
    print(f"Written: {OUTPUT_PATH}", file=sys.stderr)


if __name__ == "__main__":
    main()
